### ISSUE TITLE
grumpy unicorn

### ISSUE THREAD

**Issue by aquynh** [carstein/carstein.github.io#1]
hi Carstein,

i accidentally bumped into your post on Unicorn. thanks for your interesting comments, it helps us to understand the concerns of Unicorn users.

some comments on the content:

- on "Superflous const naming": yes, the Python API can be nicer, because so far we just ported C interface over. we even have this exact issue, but nobody stepped up yet: https://github.com/unicorn-engine/unicorn/issues/201

- on "Hooks": as primitive API, we dont want to do more, but let users code their own callbacks. if we move these "per address" callback into the core, we would have to do exactly the same thing there.

    regarding the memory hook, in the core the callback is only called on memory access instructions, but not on every instructions. and yes, this type of hook will be slower for sure.

- on "Misc" and others: again we dont want to provide higher level APIs, but intentionally focus on primitive APIs only. there might be some exceptions, but only for things that benefit a lot of users.

cheers.

**Comment by carstein** [comment]
Hi,

Thank you very much for your feedback - as stated in my post Unicorn engine works really well, and in my opinion, is currently the most approachable emulation framework out there.

Now, to your points:
- const - in my draft I even had a statement that it probably steam from the flat C namespaces, but never made it to final version. Anyhow, will take a look at the issue and see if that is something I can do in reasonable time.

- hooks - well, I was just told by someone that actually you can restrict hook to addresses in range (star,end), so maybe this would be a solution.

- misc - I understand your point here and of course if doesn't make sense to add everything but a kitchen sync. Still, I think that reading the [value] and strings would be great thing to have.
Next blog entry I will just post some code snippets how it can be done, so maybe some people will find it useful.

As a closing words - thank you very much for stopping by and sharing your point of view.
(and I apologize for lack of proper comment systems :)
